SELECT P.MECA_ID          AS MECA_ID_PADRE,
       P.MECA_NOMBRE      AS MECA_NOMBRE_PADRE,
       P.MECA_DESCRIPCION AS MECA_DESCRIPCION_PADRE,
       P.MECA_IMAGEN_URL  AS MECA_IMAGEN_URL_PADRE,
       H.MECA_ID          AS MECA_ID_HIJO,
       H.MECA_NOMBRE      AS MECA_NOMBRE_HIJO,
       H.MECA_DESCRIPCION AS MECA_DESCRIPCION_HIJO,
       H.MECA_IMAGEN_URL  AS MECA_IMAGEN_URL_HIJO,
       H.MECA_PARENT_ID   AS MECA_PARENT_ID
FROM MST_MENU_CATEGORIAS as P
         LEFT JOIN MST_MENU_CATEGORIAS as H
                   ON P.MECA_ID = H.MECA_PARENT_ID
WHERE P.MECA_ESTADO = 'A'
  AND H.MECA_ESTADO = 'A'