spring:
  application:
    name: room-service

  # ── Base de datos R2DBC (reactivo) ──────────────────────────────────────────
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hotelguestdb?sslMode=DISABLE&schema=public
    username: postgres
    password: BD1234+pg*
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  # ── SQL inicialización ─────────────────────────────────────────────────────
  sql:
    init:
      mode: never

# ── Puerto del servidor ──────────────────────────────────────────────────────
server:
  port: 8081

# ── Logs ─────────────────────────────────────────────────────────────────────
logging:
  level:
    com.hotel: DEBUG
    org.springframework.r2dbc: DEBUG
